**print a pattern**

In [42]:
row = int(input("enter number of rows"))
cols = int(input("enter number of column"))
for i in range(0 ,row):
 for j in range(0,cols):
  if i%2==0:
   if j%2==0:
    print("#",end=" ")
   else:
    print("*",end=" ")
  else:
   if j%2!=0:
    print("#",end=" ")
   else:
    print("*",end=" ") 
 print("\n")         

enter number of rows 3
enter number of column 3


# * # 

* # * 

# * # 



**NUMPY**

In [2]:
 import numpy

In [37]:
import numpy as np
arr = np.array([1,23,34,])
arr.ndim
arr.shape
arr.size
arr1 = np.full((2,4) , 8)
arr1

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [34]:
np.max(arr,axis = 0)

34

In [38]:
np.sum(arr1 , axis = 1)

array([32, 32])

In [51]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [48]:
np.reshape(1,1)

array([1])

In [53]:
np.concatenate([a,arr])

array([ 2,  4,  6,  8,  1, 23, 34])

In [55]:
import time


No Python documentation found for 'import time'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [58]:
np.linspace(2,5,5)

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [61]:
arr1.flatten()

array([8, 8, 8, 8, 8, 8, 8, 8])

In [62]:
arr1.ravel()

array([8, 8, 8, 8, 8, 8, 8, 8])

**PANDAS**

In [63]:
import pandas

In [64]:
import pandas as p

In [102]:
df = p.DataFrame(data = [[89,'a'] ,[25,'b'],[34]], index = ['punjabi','english','hindi'], columns = ['marks','grade'] )
df

marks grade
punjabi     89     a
english     25     b
hindi       34  None

In [103]:
df.sort_values(by = ['marks'])

marks grade
english     25     b
hindi       34  None
punjabi     89     a

In [105]:
df[df.isnull()]

marks grade
punjabi    NaN   NaN
english    NaN   NaN
hindi      NaN  None

In [109]:
df.describe

<bound method NDFrame.describe of          marks grade
punjabi     89     a
english     25     b
hindi       34  None>

In [111]:
df.info

<bound method DataFrame.info of          marks grade
punjabi     89     a
english     25     b
hindi       34  None>

In [89]:
import pandas as p
Idf = p.read_csv('iris.xls')
Idf

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [90]:
Id = Idf['species'].count()
Id

150

In [91]:
Idf.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [92]:
Idf.value_counts()

sepal_length  sepal_width  petal_length  petal_width  species   
4.9           3.1          1.5           0.1          setosa        3
5.8           2.7          5.1           1.9          virginica     2
              4.0          1.2           0.2          setosa        1
5.9           3.0          4.2           1.5          versicolor    1
6.2           3.4          5.4           2.3          virginica     1
                                                                   ..
5.5           2.3          4.0           1.3          versicolor    1
              2.4          3.7           1.0          versicolor    1
                           3.8           1.1          versicolor    1
              2.5          4.0           1.3          versicolor    1
7.9           3.8          6.4           2.0          virginica     1
Name: count, Length: 147, dtype: int64

In [93]:
Idf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [94]:
Idf.drop_duplicates()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

In [97]:
Idf.T

0       1       2       3       4       5       6       7    \
sepal_length     5.1     4.9     4.7     4.6     5.0     5.4     4.6     5.0   
sepal_width      3.5     3.0     3.2     3.1     3.6     3.9     3.4     3.4   
petal_length     1.4     1.4     1.3     1.5     1.4     1.7     1.4     1.5   
petal_width      0.2     0.2     0.2     0.2     0.2     0.4     0.3     0.2   
species       setosa  setosa  setosa  setosa  setosa  setosa  setosa  setosa   

                 8       9    ...        140        141        142        143  \
sepal_length     4.4     4.9  ...        6.7        6.9        5.8        6.8   
sepal_width      2.9     3.1  ...        3.1        3.1        2.7        3.2   
petal_length     1.4     1.5  ...        5.6        5.1        5.1        5.9   
petal_width      0.2     0.1  ...        2.4        2.3        1.9        2.3   
species       setosa  setosa  ...  virginica  virginica  virginica  virginica   

                    144        145        146        147        148        149  
sepal_length        6.7        6.7        6.3        6.5        6.2        5.9  
sepal_width         3.3        3.0        2.5        3.0        3.4        3.0  
petal_length        5.7        5.2        5.0        5.2        5.4        5.1  
petal_width         2.5        2.3        1.9        2.0        2.3        1.8  
species       virginica  virginica  virginica  virginica  virginica  virginica  

[5 rows x 150 columns]

In [103]:
Id = Idf['species'].value_counts()
Id

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [104]:
Idf

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
import pandas as p

In [8]:

run = [2,34,]
runs = p.Series(run)
runs

0     2
1    34
dtype: int64